name: Deploy Docker Container

on:
  workflow_run:
    workflows: ["Build and Push Docker Image"]
    types:
    - completed

jobs:
  deploy:
    runs-on: self-hosted

    steps:
    - name: Log in to Docker Hub
      run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

    - name: Pull Docker Image
      run: docker pull ${{ secrets.DOCKER_USERNAME }}/simple-html:latest

    - name: Run Docker Container
      run: |
        docker stop simple-html || true
        docker rm simple-html || true
        docker run -d --name simple-html -p 80:80 ${{ secrets.DOCKER_USERNAME }}/simple-html:latest
